language: rust
cache: cargo

install:
  - rustup component add rustfmt
  - rustup component add clippy
  - command -v cargo-audit >/dev/null 2>&1 || cargo install cargo-audit

branches:
  only:
    - develop

env:
  global:
    - RUST_BACKTRACE=1

matrix:
  include:
    - name: audit
      rust: stable
      os: linux
      script:
        - cargo audit
    - name: rustfmt
      rust: stable
      os: linux
      script:
        - cargo fmt -- --check
    - name: clippy
      rust: stable
      os: linux
      script:
        - cargo clippy
    - name: build
      rust: stable
      os: linux
      script:
        - cargo build --no-default-features --features=std --lib
        - cargo build --release
    - name: test (rustc 1.39.0)
      rust: 1.39.0
      script:
        - cargo test --release
    - name: test (rustc stable)
      rust: stable
      os: linux
      script:
        - cargo test --release
    - name: test (rustc stable/macos)
      rust: stable
      os: osx
      script:
        - cargo test --release
    - name: doc
      rust: stable
      os: linux
      script:
        - cargo doc
